### ISSUE TITLE
Investigate networktables update rate

### ISSUE THREAD

**Issue by caloisio** [1757WestwoodRobotics/2022-RapidReact#11]
Currently networktables is being used as a global key/value store for inter-submodule communication (e.g. drive subsystem with vision subsystem). Over the network, it is limited to a 10Hz update rate by default and convention. The robot control rate is 50Hz and it would be preferable for on-robot inter-submodule communication to operate at that rate at minimum.

- [ ] Investigate whether the 10Hz networktables update rate only limits network updates or local updates as well
- [ ] If the networktables rate is limited to 10Hz in all cases, investigate alternatives for inter-submodule communication (thread-safe `dict`, lightweight database, etc)

**Comment by virtuald** [comment]
10hz update rate only affects network update rate

**Comment by caloisio** [comment]
Thanks @virtuald, good to hear from an expert :smile: Per other discussions it may be somewhat of a moot point if NT-based usage incurs performance penalties that preclude heavy high-rate usage anyway.
