### ISSUE TITLE
Set motors to 0 voltage when brakes are locked (no motor fighting the brake, one controls at a time)

### ISSUE THREAD

**Issue by LandonBayer** [1757WestwoodRobotics/2022-RapidReact#69]
Climber issue

**Comment by lmaxwell24** [comment]
look into voltage control mode

**Comment by caloisio** [comment]
I believe this is addressed by our climber code calling `setNeutralOutput()`. @LandonBayer can you confirm and if so feel free to mark this issue as done and close it.

**Comment by LandonBayer** [comment]
Yup it does, this can go
