### ISSUE TITLE
Use separate classes for sim/real instead of using branches

### ISSUE THREAD

**Issue by virtuald** [1757WestwoodRobotics/2022-RapidReact#86]
For example in [Falcon](https://github.com/1757WestwoodRobotics/2022-RapidReact/blob/7e988500bd9a561e0f64d86cea6b23400e52070a/util/helpfulIO.py#L206):

```python
    def neutralOutput(self) -> None:
        if RobotBase.isReal():
            self.motor.neutralOutput()
        else:
            self.setSpeed(0)
```

Function calls in python are relatively expensive compared to other code execution, so prefer to lift them out so that they're executed less frequently (or only once if their output isn't going to change, such as the case here):

```python
    if RobotBase.isReal():
        def neutralOutput(self) -> None:
            self.motor.neutralOutput()
    else:
        def neutralOutput(self) -> None:
            self.setSpeed(0)
```

Alternatively, use completely different classes:

```python
if RobotBase.isReal():
    class Falcon:

        ...

        def neutralOutput(self) -> None:
            self.motor.neutralOutput()
else:

    class Falcon:

        ...

        def neutralOutput(self) -> None:
            self.setSpeed(0)
```

**Comment by lmaxwell24** [comment]
Resolved with #88
